name = "LabArduinoShutter"
uuid = "647f4b2c-c2a1-4835-a961-fbd06becf36e"
authors = ["Jan Kuhfeld <jan.kuhfeld@rub.de> and contributors"]
version = "1.0.0-DEV"

[deps]
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
